[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"

# Single page app support - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
